//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DeviceAssist.MesWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EventServiceHttpBinding", Namespace="http://ws.eventmanager.rockwell.com")]
    public partial class EventService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback signalEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback signalEvent2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EventService() {
            this.Url = "http://192.168.100.92:8123/soap/EventService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event signalEventCompletedEventHandler signalEventCompleted;
        
        /// <remarks/>
        public event signalEvent2CompletedEventHandler signalEvent2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.eventmanager.rockwell.com", ResponseNamespace="http://ws.eventmanager.rockwell.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void signalEvent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] string[] in1) {
            this.Invoke("signalEvent", new object[] {
                        in0,
                        in1});
        }
        
        /// <remarks/>
        public void signalEventAsync(string in0, string[] in1) {
            this.signalEventAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void signalEventAsync(string in0, string[] in1, object userState) {
            if ((this.signalEventOperationCompleted == null)) {
                this.signalEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsignalEventOperationCompleted);
            }
            this.InvokeAsync("signalEvent", new object[] {
                        in0,
                        in1}, this.signalEventOperationCompleted, userState);
        }
        
        private void OnsignalEventOperationCompleted(object arg) {
            if ((this.signalEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.signalEventCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.eventmanager.rockwell.com", ResponseNamespace="http://ws.eventmanager.rockwell.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        public string[] signalEvent2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] string[] in1) {
            object[] results = this.Invoke("signalEvent2", new object[] {
                        in0,
                        in1});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void signalEvent2Async(string in0, string[] in1) {
            this.signalEvent2Async(in0, in1, null);
        }
        
        /// <remarks/>
        public void signalEvent2Async(string in0, string[] in1, object userState) {
            if ((this.signalEvent2OperationCompleted == null)) {
                this.signalEvent2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnsignalEvent2OperationCompleted);
            }
            this.InvokeAsync("signalEvent2", new object[] {
                        in0,
                        in1}, this.signalEvent2OperationCompleted, userState);
        }
        
        private void OnsignalEvent2OperationCompleted(object arg) {
            if ((this.signalEvent2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.signalEvent2Completed(this, new signalEvent2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void signalEventCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void signalEvent2CompletedEventHandler(object sender, signalEvent2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class signalEvent2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal signalEvent2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591